name: InteractiveMatrix-Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build InteractiveMatrix
      run: |
       MSBuild.exe $Env:GITHUB_WORKSPACE\InteractiveMatrix\InteractiveMatrix.csproj /t:Restore
       MSBuild.exe $Env:GITHUB_WORKSPACE\InteractiveMatrix\InteractiveMatrix.csproj /t:Build /p:Configuration=Debug
       MSBuild.exe $Env:GITHUB_WORKSPACE\InteractiveMatrix\InteractiveMatrix.csproj /t:Build /p:Configuration=Release

    - name: Build MHC2Gen
      run: |
       cmd.exe /c md $Env:GITHUB_WORKSPACE\lcms2\bin\
       curl.exe -L -O https://github.com/dantmnf/AMDColorTweaks/releases/download/ci-build/AMDColorTweaks.zip --output-dir $Env:GITHUB_WORKSPACE\lcms2\bin\
       tar.exe -xzvf $Env:GITHUB_WORKSPACE\lcms2\bin\AMDColorTweaks.zip -C $Env:GITHUB_WORKSPACE\lcms2\bin\
       MSBuild.exe $Env:GITHUB_WORKSPACE\MHC2Gen\MHC2Gen.csproj /t:Restore
       MSBuild.exe $Env:GITHUB_WORKSPACE\MHC2Gen\MHC2Gen.csproj /t:Build /p:Configuration=Debug
       MSBuild.exe $Env:GITHUB_WORKSPACE\MHC2Gen\MHC2Gen.csproj /t:Build /p:Configuration=Release

    - uses: actions/upload-artifact@master
      with:
        name: "InteractiveMatrix" 
        path: InteractiveMatrix\bin\*

    - uses: actions/upload-artifact@master
      with:
        name: "MHC2Gen" 
        path: MHC2Gen\bin\*
